services:
  nginx:
    container_name: ${SERVICE_NAME_PREFIX}-${NGINX_SERVICE_NAME}
    build:
      dockerfile: ./nginx/Dockerfile
    networks:
      - network
    env_file: ./.env
    secrets:
      - backend-ca.crt
      - nginx.crt
      - nginx.key
    ports:
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    container_name: ${SERVICE_NAME_PREFIX}-${BACKEND_SERVICE_NAME}
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - network
    env_file: ./.env
    secrets:
      - backend.key
      - backend.crt
    volumes:
      - sqlite-db:${BACKEND_CONTAINER_DB_VOL_PATH}
    expose:
      - ${BACKEND_FASTIFY_PORT}
    restart: unless-stopped

# Explicitly specifying a Docker network for containers to communicate on.
networks:
  network:
    driver: bridge

secrets:
  backend-ca.crt:
    file: ${SECRETS_DIR}/${SECRET_BACKEND_CA_CRT_FILENAME}
  nginx.crt:
    file: ${SECRETS_DIR}/${SECRET_NGINX_CRT_FILENAME}
  nginx.key:
    file: ${SECRETS_DIR}/${SECRET_NGINX_KEY_FILENAME}
  backend.key:
    file: ${SECRETS_DIR}/${SECRET_BACKEND_KEY_FILENAME}
  backend.crt:
    file: ${SECRETS_DIR}/${SECRET_BACKEND_CRT_FILENAME}

volumes:
  sqlite-db:
