services:
  nginx:
    container_name: "${NGINX_SERVICE_NAME}"
    build:
      dockerfile: ./nginx/Dockerfile
    networks:
      - network
    env_file: ./.env
    secrets:
      - ft_transcendence.crt
      - ft_transcendence.key
    ports:
      - "443:443"
    restart: unless-stopped
  backend:
    container_name: "${BACKEND_SERVICE_NAME}"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - network
    env_file: ./.env
    expose:
      - "${BACKEND_FASTIFY_PORT}"
    restart: unless-stopped

# Explicitly specifying a Docker network for containers to communicate on.
networks:
  network:
    driver: bridge

secrets:
  ft_transcendence.crt:
    file: ./secrets/ft_transcendence.crt
  ft_transcendence.key:
    file: ./secrets/ft_transcendence.key
